// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayStudiosCodingChallenge.Data;

#nullable disable

namespace PlayStudiosCodingChallenge.Data.Migrations
{
    [DbContext(typeof(QuestStateDbContext))]
    partial class QuestStateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PlayStudiosCodingChallenge.Data.Models.PlayerQuestState", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("LastMilestoneIndexCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalQuestPointsEarned")
                        .HasColumnType("REAL");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerQuestStates");
                });
#pragma warning restore 612, 618
        }
    }
}
